services:

  mysql:
    image: mysql:8.0
    container_name: beautylink-mysql
    restart: always
    environment:
      MYSQL_DATABASE: beautylink
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: beautylink
      MYSQL_PASSWORD: beautylink
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: beautylink-backend
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: beautylink
      DB_USERNAME: beautylink
      DB_PASSWORD: beautylink

  frontend:
    build:
      context: ./frontend
    container_name: beautylink-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data: